language: java

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: test
      script:
        - mvn clean verify
    - stage: deploy
      if: branch = master AND type IN (push)
      jdk: oraclejdk8
      script:
        - mvn clean source:jar javadoc:javadoc deploy --settings travis_settings.xml

# travis encrypt -r bootique/bootique "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r bootique/bootique "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: "CDO2VNKgMS+oJiRD2I93SSKaA9sLvLTjrWMa6YlD6y90OHI9q3ajiKepJc9ejxkOVN0PEX9K88DANO3AF2LgkvfliW8qswOrOXav3QzNfAJxhjpkrGufv95hGNhk5h05SARxGL+/MqwrNUQcZnko3Gmt4LvIlEFAW1ZKE3NNdJmq5Q2UOAnyuyNUkFMDcEHdnVKsNn0T8BUi3wCp4aqsO794tVMi+oYAeFlQPSCktHmDtlDsAr9i+Qpi7Lr0DZaWN6+X0N+icivRrUvVwsWJqvbYGtElgeAFbrh6yVLPKawOrWUZzi5XYNPwR1XKQT0PQW9YGtWbvK0cqDc30HFGbs8OXQAy6pH9abU60J+qY+oBEls1eqzynSxxDi0bu5TM2Md9SR64yBlNPD7wu2jdxRjdbcF2tpBLzhEnQrC+yhfR+w3laIzKVX/BXkqPcD6z6hLYDeXZdwrwff06vimAodGd7SJ0NvpEUgHrKqreGuASjCI8aePE9Y1IbxP5daNCprXVTe0kwLM9CcARvPQEAZvnYpcYsNbesgX/CbSdIybvFbdO/9mZ/waIXN5ZYQJOXeqRIIVPk02Pl2Kj+SkDv4N9PaxhrHQAUop/p15Ysplz8ggRMYhD/4Te3DAB+r3B4y7YPZXssllilxbIG5Wr3ZMgUXxBLzwjJck43PXHjQw="
    - secure: "Y8sVrrCYoKN/P8kfOQ7AFjjLq95ZRZtkDPbQQGXuKd8HFujTpqXeCLbm/eFXo3gNewQ5zWNgpOFN2N5gaGdV3Ku+m6dRsnBoQbHYAuR3MhotEjSZymHp1aVTGGWMJsGmiM+saCXtC+sUQcE6qUJjYsrhiyAfyU+6wWFGr5G9k8dUO7YyOgJryzSx70swLeoxiYhEZq2hQ66mifaaBuQxBbNXSLpsY9g8XxkwLNBycoTzhwhldvDDfeEeK4bvkb4lBSSvGlHUZCvG9K4gT/NunNVAoyjo1pumP9cuvWglRVodiT1k8yhTbFGfeB3KwWgN8J+mt93z8XcL1iMzZ8LcaTzhtNBT6zNOeE48JKhOyqAJOWH1sASh+SfiAG0UuuLXDkg56c+bJO426/gIeLxrXZMX6hkN6wII6L52shGgadfypn0frw2Rw6oEEk7oGHhAv3NtOYnlGt5meZpNNAEdwlVzbUXaFXh8XgaHsApg1X0kPK2yYdImEWq3pa7iQyB1GZPjctNzbhk2Vgjwk91kPj2RYaBd86BkIQGUfwdb0zIMCCjDXhALhbomei7fVXHSg5XcF4ZWg/2Z7s2A1C/5zgcDzdQWB/I0JQB+dMuTIm090bJ/mva8GORz/Mq8XVxoBMziic/UM6gtjmA8ft0+Prpm43NoHVjAKdX4vncJL0w="
