name: 'build test deploy'

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-24.04
    name: JDK ${{ matrix.java }}
    strategy:
      matrix:
        java: [ 21, 24 ]

    steps:
      - name: Checkout...
        uses: actions/checkout@v4

      - name: Set up JDK...
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test...
        run: mvn -ntp clean verify

  deploy:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout...
        uses: actions/checkout@v4

      # this action exports env.POM_VERSION variable
      - name: Export Maven coordinates...
        uses: bootique-tools/export-maven-coordinates-action@v1

      - name: Set up JDK...
        uses: actions/setup-java@v4
        # skip this for the release versions
        if: contains(env.POM_VERSION, '-SNAPSHOT')
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Deploy...
        run: mvn -ntp clean source:jar-no-fork javadoc:jar deploy -DskipTests --settings .github/workflows/maven_settings.xml
        # skip this for the release versions
        if: contains(env.POM_VERSION, '-SNAPSHOT')
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
